### ISSUE TITLE
Flask Login Manager

### ISSUE THREAD

**Issue by loki4514** [loki4514/webdev1#1]
/Admin
/Employee 
(two different routes)
issue is i want to use two different login manager(admin has it's own login manager and employee has it's own login manager). so i defined two different login manager, but employee login manager is overwriting the admin's login manager.
1) How to solve this issue?
2) Can i able define or use two different login managers in flask application. If possible how to define.

**Comment by Aliqyan-21** [comment]
In Flask, you can use multiple login managers by creating separate instances of the LoginManager class for each type of user (admin and employee). By doing so, you can have different configurations and behavior for each login manager.

**See like this :**

from flask import Flask
from flask_login import LoginManager

app = Flask(__name__)

# Create the admin login manager
admin_login_manager = LoginManager()
admin_login_manager.init_app(app)
admin_login_manager.login_view = 'admin_login'  # Specify the login view for the admin

# Create the employee login manager
employee_login_manager = LoginManager()
employee_login_manager.init_app(app)
employee_login_manager.login_view = 'employee_login'  # Specify the login view for the employee

# Now you can define your views and login routes for both admin and employee

@app.route('/admin/login')
def admin_login():
    # Admin login view logic here
    pass

@app.route('/employee/login')
def employee_login():
    # Employee login view logic here
    pass

# Rest of your Flask application code...

By using separate login managers, you should be able to have distinct login functionality for admin and employee users without overwriting each other 😃.

All the best 👍🏼

**Comment by loki4514** [comment]
thanks mate..
