### ISSUE TITLE
Flask 

### ISSUE THREAD

**Issue by loki4514** [loki4514/webdev1#2]
When a user logs out, a certain page is redirected, and when I use the browser's back button, the contents are seen. Why is that so?

@admins.route("/logout")

def logout():
    logout_user()
    session.clear()
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    return redirect(url_for('main.index'))

**Comment by WaqarAnwar** [comment]
You can try this: 
response.headers.add('Cache-Control', 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0')
